// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGNQcw5YyJgMp2gsS5JcDjeJs4xdRHAjY',
    appId: '1:610386003117:web:8b34829ba7fcb32ad07224',
    messagingSenderId: '610386003117',
    projectId: 'my-autoconnect',
    authDomain: 'my-autoconnect.firebaseapp.com',
    storageBucket: 'my-autoconnect.appspot.com',
    measurementId: 'G-P6B826T02H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVfbYOPiY9_CHGJa8egDFAM9MfE8ymIwY',
    appId: '1:610386003117:android:16be8e2655d014eed07224',
    messagingSenderId: '610386003117',
    projectId: 'my-autoconnect',
    storageBucket: 'my-autoconnect.appspot.com',
  );
}
